import Head from "next/head";
import Navbar from "./components/Navbar";
import Carousel from "./components/Carousel";
import Cards from "./components/Cards";
import Progressbar from "./components/Progressbar";
import Grid from "./components/Grid";
import Footer from "./components/Footer";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>ZET : Become a Certified Financial Advisor and Earn Big</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar/>
        <Carousel/>
        <Cards/>
        <Progressbar/>
        <Grid/>
        <Footer/>
      </main>
    </>
  );
}
